repo_url: https://github.com/Interacao-Humano-Computador/2024.1-Prefeitura-Lagoa-da-Prata
repo_name: Prefeitura de Lagoa da Prata
site_name: Prefeitura Municipal de Lagoa da Prata


markdown_extensions:
  - md_in_html
  - pymdownx.extra
  - attr_list
  - pymdownx.magiclink

plugins:
  - search
  - open-in-new-tab

nav:
  - Início: index.md
  - Planejamento:
    - Heatmap: planejamento/heatmap.md
    - Cronograma Planejado: planejamento/cronograma_planejado.md
    - Cronograma Executado: planejamento/cronograma_executado.md
    - Processos de Design: planejamento/processos_de_design.md
    - Ferramentas do Projeto: planejamento/ferramentas_do_projeto.md
    - Sites Avaliados: planejamento/sites_avaliados.md    
    - Site Escolhido: planejamento/site_escolhido.md
  - Reuniões:
    - Reunião 1: reunioes/reuniao_1.md
    - Reunião 2: reunioes/reuniao_2.md
  - Apresentações:
    - Apresentação 1: apresentacoes/apresentacao1.md
  - Análise de requisitos:
    - Aspectos Éticos: requisitos/aspectos-eticos.md
    - Questionario: requisitos/questionario.md
    - Entrevista: requisitos/entrevista.md
    - Perfil do Usuário: requisitos/perfil-do-usuario.md
    - Personas: requisitos/personas.md
    - Cenários: requisitos/cenarios.md
    - Análise de Tarefas: requisitos/analise-tarefas.md
    - Metas de Usabilidade: requisitos/metas-usabilidade.md
    - Principios Gerais: requisistos/principios.md
    - Guias de Estilo: requisitos/guia-de-estilo.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  langage: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Trocar pro modo escuro
      primary: teal
      accent: teal
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Trocar pro modo claro
      primary: teal
      accent: teal

    

