repo_url: https://github.com/Interacao-Humano-Computador/2024.1-Prefeitura-Lagoa-da-Prata
repo_name: Prefeitura de Lagoa da Prata
site_name: Prefeitura Municipal de Lagoa da Prata


markdown_extensions:
  - md_in_html
  - pymdownx.extra
  - attr_list
  - pymdownx.magiclink

plugins:
  - search
  - open-in-new-tab

nav:
  - Início: index.md
  - Planejamento:
    - Heatmap: planejamento/heatmap.md
    - Cronograma Planejado: planejamento/cronograma_planejado.md
    - Cronograma Executado: planejamento/cronograma_executado.md
    - Processos de Design: planejamento/processos_de_design.md
    - Ferramentas do Projeto: planejamento/ferramentas_do_projeto.md
    - Metodologia: planejamento/metodologia.md
    - Sites Avaliados: planejamento/sites_avaliados.md    
    - Site Escolhido: planejamento/site_escolhido.md
  - Reuniões:
    - Reunião 1: reunioes/reuniao_1.md
    - Reunião 2: reunioes/reuniao_2.md
  - Apresentações:
    - Apresentação 1: apresentacoes/apresentacao1.md
    - Apresentação 2: apresentacoes/apresentacao2.md
    - Apresentação 3: apresentacoes/apresentacao3.md
  - Análise de requisitos I:
    - Aspectos Éticos: requisitos1/aspectos-eticos.md
    - Questionario: requisitos1/questionario.md
    - Entrevista: requisitos1/entrevista.md
    - Perfil do Usuário: requisitos1/perfil-do-usuario.md
    - Personas: requisitos1/personas.md
    - Cenários: requisitos1/cenarios.md
    - Análise de Tarefas: requisitos1/analise-tarefas.md
  - Análise de requisitos II:
      - Principios Gerais: requisitos2/principios_gerais.md
      - Metas de Usabilidade: requisitos2/metas-usabilidade.md
      - Guias de Estilo: requisitos2/guia-de-estilo.md
      - Caracteristicas da Plataforma Para o Projeto: requisitos2/caracteristicas.md




theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  langage: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Trocar pro modo escuro
      primary: teal
      accent: teal
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Trocar pro modo claro
      primary: teal
      accent: teal

    

