repo_url: https://github.com/Interacao-Humano-Computador/2024.1-Prefeitura-Lagoa-da-Prata
repo_name: Prefeitura Lagoa da Prata
site_name: Prefeitura de Lagoa da Prata


markdown_extensions:
  - md_in_html
  - pymdownx.extra
  - attr_list

plugins:
  - search
  - open-in-new-tab

nav:
  - Início: index.md
  - Planejamento:
    - Cronograma Planejado: planejamento/cronograma_planejado.md
    - Cronograma Executado: planejamento/cronograma_executado.md
    - Processos de Design: planejamento/processos_de_design.md
    - Ferramentas do Projeto: planejamento/ferramentas_do_projeto.md
    - Sites Avaliados: planejamento/sites_avaliados.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  langage: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Trocar pro modo escuro
      primary: teal
      accent: teal
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Trocar pro modo claro
      primary: teal
      accent: teal

    

